### ISSUE TITLE
CustomPostsController Error when setting blog_id

### ISSUE THREAD

**Issue by cdesch** [CultivateLabs/storytime#164]
When creating a new blog entry using a custom post type, I receive a `uninitialized constant Blog` error when going to the `new` view. It looks like it is trying to set the `blog_id` to "blog" instead of the actual id.

Is there a view I was suppose to customize in addition to the `_your_post_type_fields.html.erb`?

```
Started GET "/p/storytime/blogs/blog/article_posts/new" for 127.0.0.1 at 2015-05-10 10:33:11 -0400
Processing by Storytime::Dashboard::CustomPostsController#new as HTML
  Parameters: {"blog_id"=>"blog"}
   (0.1ms)  SELECT COUNT(*) FROM "storytime_sites"
  Storytime::Site Load (0.1ms)  SELECT  "storytime_sites".* FROM "storytime_sites" WHERE "storytime_sites"."custom_domain" = ? LIMIT 1  [["custom_domain", "localhost"]]
  User Load (0.1ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = ?  ORDER BY "users"."id" ASC LIMIT 1  [["id", 1]]
  CACHE (0.0ms)  SELECT COUNT(*) FROM "storytime_sites"
   (0.1ms)  SELECT COUNT(*) FROM "storytime_memberships" WHERE "storytime_memberships"."site_id" = ? AND "storytime_memberships"."user_id" = ?  [["site_id", 1], ["user_id", 1]]
Completed 500 Internal Server Error in 4ms (ActiveRecord: 0.3ms)
** [Airbrake] Notice was not sent due to configuration:         
  Environment Monitored? false         
  API key set? false

NameError - uninitialized constant Blog:
  activesupport (4.2.1) lib/active_support/dependencies.rb:533:in `load_missing_constant'
  activesupport (4.2.1) lib/active_support/dependencies.rb:184:in `const_missing'
  activesupport (4.2.1) lib/active_support/inflector/methods.rb:261:in `block in constantize'
  activesupport (4.2.1) lib/active_support/inflector/methods.rb:259:in `constantize'
  activesupport (4.2.1) lib/active_support/core_ext/string/inflections.rb:66:in `constantize'
  storytime (2.0.0) app/controllers/storytime/dashboard/custom_posts_controller.rb:36:in `current_post_type'
  storytime (2.0.0) app/controllers/storytime/dashboard/custom_posts_controller.rb:6:in `new'
  actionpack (4.2.1) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.2.1) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.1) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
  activesupport (4.2.1) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
  activesupport (4.2.1) lib/active_support/callbacks.rb:313:in `block (2 levels) in halting'
  storytime (2.0.0) app/controllers/storytime/application_controller.rb:65:in `scope_current_site'
  activesupport (4.2.1) lib/active_support/callbacks.rb:432:in `block in make_lambda'
  activesupport (4.2.1) lib/active_support/callbacks.rb:312:in `block in halting'
  activesupport (4.2.1) lib/active_support/callbacks.rb:497:in `block in around'
  activesupport (4.2.1) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:92:in `_run_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_process_action_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.1) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.1) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.1) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.1) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.1) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.1) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.1) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:43:in `serve'
  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:819:in `call'
  railties (4.2.1) lib/rails/engine.rb:518:in `call'
  railties (4.2.1) lib/rails/railtie.rb:194:in `method_missing'
  actionpack (4.2.1) lib/action_dispatch/routing/mapper.rb:51:in `serve'
  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:819:in `call'
  warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.3) lib/warden/manager.rb:34:in `call'
  rack (1.6.1) lib/rack/etag.rb:24:in `call'
  rack (1.6.1) lib/rack/conditionalget.rb:25:in `call'
  rack (1.6.1) lib/rack/head.rb:13:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.1) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.1) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.1) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:649:in `call'
  activerecord (4.2.1) lib/active_record/migration.rb:378:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:88:in `_run_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_call_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  airbrake (4.1.0) lib/airbrake/rails/middleware.rb:13:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  web-console (2.1.2) lib/web_console/middleware.rb:37:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.1) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.1) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.1) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.1) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.1) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.1) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/static.rb:113:in `call'
  rack (1.6.1) lib/rack/sendfile.rb:113:in `call'
  airbrake (4.1.0) lib/airbrake/user_informer.rb:16:in `_call'
  airbrake (4.1.0) lib/airbrake/user_informer.rb:12:in `call'
  railties (4.2.1) lib/rails/engine.rb:518:in `call'
  railties (4.2.1) lib/rails/application.rb:164:in `call'
  rack (1.6.1) lib/rack/content_length.rb:15:in `call'
  thin (1.6.3) lib/thin/connection.rb:86:in `block in pre_process'
  thin (1.6.3) lib/thin/connection.rb:84:in `pre_process'
  thin (1.6.3) lib/thin/connection.rb:53:in `process'
  thin (1.6.3) lib/thin/connection.rb:39:in `receive_data'
  eventmachine (1.0.7) lib/eventmachine.rb:187:in `run'
  thin (1.6.3) lib/thin/backends/base.rb:73:in `start'
  thin (1.6.3) lib/thin/server.rb:162:in `start'
  rack (1.6.1) lib/rack/handler/thin.rb:19:in `run'
  rack (1.6.1) lib/rack/server.rb:286:in `start'
  railties (4.2.1) lib/rails/commands/server.rb:80:in `start'
  railties (4.2.1) lib/rails/commands/commands_tasks.rb:80:in `block in server'
  railties (4.2.1) lib/rails/commands/commands_tasks.rb:75:in `server'
  railties (4.2.1) lib/rails/commands/commands_tasks.rb:39:in `run_command!'
  railties (4.2.1) lib/rails/commands.rb:17:in `<top (required)>'
  bin/rails:4:in `<top (required)>'
  -e:1:in `<main>'
```

**Comment by dvanderbeek** [comment]
It looks like the current_post_type method is the problem. It's pulling the 4th segment from the url and trying to Constantine that, but that will break if you have storytime mounted at a path like /p/storytime. We will have to come up with a better solution.



—

**Comment by dvanderbeek** [comment]
For now you could probably copy the dashboard custom posts controller into your host app and modify that method to use the right segment of your url



—

**Comment by cdesch** [comment]
Let me give that a shot.

**Comment by eanlain** [comment]
@cdesch added a fix into `dev`. Let us know if that fixes this issue. Thanks!

**Comment by cdesch** [comment]
Think this issue can be closed due to age. Thanks
